server.port=8083
spring.application.name=chat-service
server.servlet.context-path=${SERVER_CONTEXT_PATH:}
spring.redis.cluster.nodes=${SPRING_REDIS_CLUSTER_NODES:localhost:7000,localhost:7001,localhost:7002,localhost:7003,localhost:7004,localhost:7005}

room.service.base-url=${ROOM_SERVICE_BASE_URL:http://localhost:8082}
room.service.connect-timeout-ms=1000
room.service.read-timeout-ms=3000

chat.stream.redis.host=${CHAT_STREAM_REDIS_HOST:localhost}
chat.stream.redis.port=${CHAT_STREAM_REDIS_PORT:6379}
chat.stream.key-prefix=chat:stream:room:

chat.pubsub.publish.retry.max-attempts=3
chat.pubsub.publish.retry.backoff-ms=200
